# - Try to find OpenHaptics libHD
# Once done this will define
#  OPENHAPTICS_FOUND - System has libHD
#  OPENHAPTICS_INCLUDE_DIR - The libHD include directories
#  OPENHAPTICS_LIBRARIES - The libraries needed to use libHD

IF(WIN32)
    FIND_PATH(HD_INCLUDE_DIR NAMES "HD/hd.h"
        PATHS $ENV{OPENHAPTICS_BASE}/include $ENV{OH_SDK_BASE}/include)
    FIND_LIBRARY(HD_LIBRARY NAMES HD
        PATHS $ENV{OPENHAPTICS_BASE}/lib $ENV{OH_SDK_BASE}/lib
        PATH_SUFFIXES w32 x64 w32/ReleaseAcademicEdition x64/ReleaseAcademicEdition)
ELSE(WIN32)
    FIND_PATH(HD_INCLUDE_DIR "HD/hd.h")
    FIND_LIBRARY(HD_LIBRARY NAMES HD)
ENDIF(WIN32)

# handle the QUIETLY and REQUIRED arguments and set OPENHAPTICS_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENHAPTICS DEFAULT_MSG HD_LIBRARY HD_INCLUDE_DIR)

IF(OPENHAPTICS_FOUND)
  SET(OPENHAPTICS_LIBRARIES ${HD_LIBRARY})
  SET(OPENHATPICS_INCLUDE_DIR ${HD_INCLUDE_DIR})
ENDIF(OPENHAPTICS_FOUND)

MARK_AS_ADVANCED(HD_LIBRARY HD_INCLUDE_DIR)

